name: Compilar vulnerable.c a vuln.exe

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Configurar entorno MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    - name: Compilar vulnerable.c a vuln.exe
      run: |
        gcc vulnerable.c -o vuln.exe
        
    - name: Subir vuln.exe como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: vuln-executable
        path: vuln.exe
