name: Compilar vulnerable.c a vuln.exe

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # También funciona con ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar MinGW-w64 (según documentación)
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64  # Por defecto, pero lo dejamos explícito
          static: 1     # Habilita el workaround para libwinpthread-1.dll
          cc: 0         # No necesitamos alias cc/c++

      - name: Verificar instalación
        run: |
          x86_64-w64-mingw32-gcc --version

      - name: Compilar vulnerable.c
        run: |
          x86_64-w64-mingw32-gcc vulnerable.c -o vuln.exe -Wall -O2

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: vuln-executable
          path: vuln.exe
