name: Compilar vulnerable.c a vuln.exe

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Install Chocolatey
      shell: pwsh
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install MinGW
      shell: pwsh
      run: choco install mingw -y --no-progress

    - name: Add MinGW to PATH
      shell: pwsh
      run: |
        $mingwPath = "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin"
        echo "::add-path::$mingwPath"

    - name: Compilar vulnerable.c a vuln.exe
      shell: cmd
      run: gcc vulnerable.c -o vuln.exe
        
    - name: Subir vuln.exe como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: vuln-executable
        path: vuln.exe
